### ISSUE TITLE
community-ee: Address comments/concerns about implementation

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/images#64]
Address comments raised in community-ee PR, in particular https://github.com/ansible-community/images/pull/61#discussion_r1296362165 and others.

**Comment by Andersson007** [comment]
https://github.com/ansible-community/images/pull/65

**Comment by samccann** [comment]
@anweshadas @Andersson007 - Is there anything left to do here or can we close this issue?

**Comment by Andersson007** [comment]
@samccann it's old, feel free to close:)
