### ISSUE TITLE
Some images do not work with podman in github actions

### ISSUE THREAD

**Issue by dmsimard** [ansible-community/images#9]
I am not certain if we've found the actual root cause but @felixfontein found that some images (namely Ubuntu 20.04, Debian Bullseye, Archlinux) do not work with podman in GitHub action workflows.

We are working around the issue by pushing the image to a local Docker registry and then using ansible-test with Docker instead of podman but it would be nice to get to the bottom of it so they would work anywhere.

Example here:
https://github.com/ansible-community/images/blob/68b19f3a8909290a2118bf85b9961efb46a7e126/.github/workflows/ansible-test.yml#L43-L54

**Comment by gotmax23** [comment]
What are the failures? Does it work if you add

```
      # This is necessary to allow running systemd in rootless containers.
      - name: Start systemd user service
        run: |
          loginctl enable-linger runner
          sleep 1
```

to the Github Action before running `ansible-test`?

**Comment by dmsimard** [comment]
Hey @gotmax23, thanks for the potential hint -- I looked at @felixfontein's PR and commented on the failure: https://github.com/ansible-community/images/pull/24#issuecomment-1197609191

**Comment by felixfontein** [comment]
This might no longer be a problem now that ansible-test had the extensive container handling upgrade.

**Comment by felixfontein** [comment]
At least CI of this repo runs tests both with docker and podman, and they pass. You might need to use `ubuntu-2404` instead of `ubuntu-latest` (which is still 22.04 and has a very old podman) though.
